-- CREAR USUARIO REPLICADOR
CREATE USER 'replicador'@'%' IDENTIFIED BY '1234';
GRANT REPLICATION SLAVE ON *.* TO 'replicador'@'%';

-- EJEMPLO FRAGMENTACIÓN HORIZONTAL
CREATE TABLE pedidos_recientes AS
SELECT * FROM Pedidos WHERE fecha >= NOW() - INTERVAL 6 MONTH;

CREATE TABLE pedidos_historicos AS
SELECT * FROM Pedidos WHERE fecha < NOW() - INTERVAL 6 MONTH;